name: Weibo Sign Chaohua

# 在每天的UTC时间16:10，即北京时间00:10触发
on:
  schedule:
    - cron: '10 16 * * *'  # UTC时间 16:10, 北京时间 00:10

jobs:
  sign:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 拉取仓库中的代码

    - name: Set up Python
      uses: actions/setup-python@v3  # 设置Python环境
      with:
        python-version: '3.x'  # 选择你需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖（假设你有 requirements.txt 文件）

    - name: Run the weibo sign script
      run: |
        python weibo_sign_chaohua.py  # 运行签到脚本
