name: Weibo Sign Chaohua

# 使用 `schedule` 事件，每天在凌晨12:05触发
on:
  schedule:
    - cron: '40 7 * * *'  # 使用CRON表达式，每天0:05触发（UTC时间）

jobs:
  sign:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 拉取仓库中的代码

    - name: Set up Python
      uses: actions/setup-python@v3  # 设置Python环境
      with:
        python-version: '3.x'  # 选择你需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 假设你有一个requirements.txt文件

    - name: Run the weibo sign script
      run: |
        python weibo_sign_chaohua.py  # 运行签到脚本

