name: Weibo Sign Chaohua

# 在每天的UTC时间16:10，即北京时间00:10触发
on:
  schedule:
    - cron: '20 16 * * *'  # UTC时间 16:10, 北京时间 00:10

jobs:
  sign:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 拉取仓库中的代码

    - name: Set up Python
      uses: actions/setup-python@v3  # 设置Python环境
      with:
        python-version: '3.x'  # 选择你需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖（假设你有 requirements.txt 文件）

    # 读取 GitHub Secrets 中的 STREAK_HISTORY 并设置为环境变量
    - name: Load streak history from secrets
      run: echo "STREAK_HISTORY=${{ secrets.STREAK_HISTORY }}" >> $GITHUB_ENV

    - name: Run the weibo sign script
      run: |
        python weibo_sign_chaohua.py  # 运行签到脚本

    # 更新签到后的 streak 历史到 GitHub Secrets
    - name: Save streak history to secrets
      run: |
        echo "STREAK_HISTORY=$(cat $GITHUB_ENV | grep STREAK_HISTORY | cut -d'=' -f2)"  # 获取签到后的 STREAK_HISTORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 更新 Secrets
      if: always()  # 无论签到是否成功，始终更新历史
